# .circleci/config.yml file
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:18    
    working_directory: ~/app
    environment:
      MY_VAR: "my-value"
    steps:
      - checkout
      - run: echo $MY_VAR
      - run: npm install
      - run: npm run start